name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: node22
    steps:
      - name: Verify Docker availability
        run: |
          if ! command -v docker >/dev/null 2>&1; then
            echo "✗ docker CLI not found"
            exit 1
          fi
          if ! docker info >/dev/null 2>&1; then
            echo "✗ docker daemon not reachable. Check /var/run/docker.sock and privileges."
            docker version || true
            ls -l /var/run/docker.sock || true
            id || true
            exit 1
          fi
          echo "✓ Docker is ready"

      # 仅用于个人使用，因为我的博客实际上在blog分支
      - name: check_branch
        run: |
          if [ -n "$REAL_TARGET_BRANCH" ]; then
            CURRENT_BRANCH="${{ gitea.ref }}"
            CURRENT_BRANCH="${CURRENT_BRANCH#refs/heads/}"
            echo "Current branch: $CURRENT_BRANCH"
            echo "Expected branch: $REAL_TARGET_BRANCH"
            if [ "$CURRENT_BRANCH" = "$REAL_TARGET_BRANCH" ]; then
              echo "✓ Branch check passed"
            else
              echo "✗ Branch mismatch!"
              exit 1
            fi
          else
            echo "REAL_TARGET_BRANCH not set, skipping branch check"
          fi
        env:
          REAL_TARGET_BRANCH: ${{ secrets.REAL_TARGET_BRANCH }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: "pnpm"

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build project
        run: pnpm build
        env:
          CLOUDFLARE_D1_TOKEN: ${{ secrets.CLOUDFLARE_D1_TOKEN }}
          CLOUDFLARE_D1_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_D1_ACCOUNT_ID }}
          CLOUDFLARE_D1_DATABASE_ID: ${{ secrets.CLOUDFLARE_D1_DATABASE_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: nuxt3-blog:latest

      - name: Deploy Docker container
        run: |
          # Stop and remove existing container
          docker ps -q --filter "name=nuxt3-blog-app" | xargs -r docker stop || true
          docker ps -aq --filter "name=nuxt3-blog-app" | xargs -r docker rm || true

          # Run new container
          docker run -d \
            --name=nuxt3-blog-app \
            --restart=always \
            -e CLOUDFLARE_D1_TOKEN=${{ secrets.CLOUDFLARE_D1_TOKEN }} \
            -e CLOUDFLARE_D1_ACCOUNT_ID=${{ secrets.CLOUDFLARE_D1_ACCOUNT_ID }} \
            -e CLOUDFLARE_D1_DATABASE_ID=${{ secrets.CLOUDFLARE_D1_DATABASE_ID }} \
            -p 127.0.0.1:8451:3000 \
            nuxt3-blog:latest
